apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: batching-secrets
  namespace: bitcert-attest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bee-demo-store
  target:
    name: batching-secrets
  data:
  - secretKey: BITCERT_DATABASE_URL
    remoteRef:
      key: bitcert/dev/batching/db
      property: BITCERT_DATABASE_URL
  - secretKey: BITCERT_NATS_URL
    remoteRef:
      key: bitcert/dev/batching/nats
      property: BITCERT_NATS_URL
  - secretKey: BITCERT_PORT
    remoteRef:
      key: bitcert/dev/batching/net
      property: BITCERT_PORT
  - secretKey: BITCERT_NATS_STREAM
    remoteRef:
      key: bitcert/dev/batching/nats
      property: BITCERT_NATS_STREAM
