apiVersion: batch/v1
kind: Job
metadata:
  name: batching-migrate-f9028cae8051
  namespace: bitcert-attest
  labels:
    bee.dev/module: batching
    bee.dev/mighash: f9028cae8051
  annotations:
    argocd.argoproj.io/sync-wave: '-98'
    argocd.argoproj.io/sync-options: Replace=true
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: flyway
        image: flyway/flyway:10-alpine
        args:
        - -url=jdbc:postgresql://postgres.bee-substrate.svc.cluster.local:5432/bee
        - -user=bee
        - -password=bee-demo
        - -connectRetries=30
        - -table=flyway_history_batching
        - -locations=filesystem:/sql
        - -baselineOnMigrate=true
        - migrate
        volumeMounts:
        - name: sql
          mountPath: /sql
      volumes:
      - name: sql
        configMap:
          name: batching-migrations
