apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingestion-secrets
  namespace: bitcert-attest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bee-demo-store
  target:
    name: ingestion-secrets
  data:
  - secretKey: BITCERT_DATABASE_URL
    remoteRef:
      key: bitcert/dev/ingestion/db
      property: BITCERT_DATABASE_URL
  - secretKey: BITCERT_NATS_URL
    remoteRef:
      key: bitcert/dev/ingestion/nats
      property: BITCERT_NATS_URL
  - secretKey: BITCERT_DEV_EXCHANGE_ID
    remoteRef:
      key: bitcert/dev/ingestion/dev
      property: BITCERT_DEV_EXCHANGE_ID
  - secretKey: BITCERT_DEV_AUDIT_FIRM_ID
    remoteRef:
      key: bitcert/dev/ingestion/dev
      property: BITCERT_DEV_AUDIT_FIRM_ID
  - secretKey: BITCERT_PORT
    remoteRef:
      key: bitcert/dev/ingestion/net
      property: BITCERT_PORT
