apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: ann-bitcert-attest-events
  namespace: bitcert-attest
spec:
  name: ANN_BITCERT_ATTEST_EVENTS
  subjects:
  - attest.>
  storage: file
  replicas: 1
