apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
      - name: hello
        image: ghcr.io/jbyee-test-org/bitcert/hello@sha256:58c49ad878618d3556d1f8d7cac46b15501a43c0f153475f4c7db941012aa362
        ports:
        - containerPort: 8080
