apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
      - name: hello
        image: ghcr.io/jbyee-test-org/bitcert/hello@sha256:571b0163b71a0d8c8fa61881398d3503af573333f27a3f295b7523afaa0b31e6
        ports:
        - containerPort: 8080
