apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
    spec:
      containers:
      - name: hello
        image: ghcr.io/jbyee-test-org/bitcert/hello@sha256:003e973cd9297ad3f455e4716f159a03ccbd790b6972e81211554a8403e3dd55
        ports:
        - containerPort: 8080
