apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-data
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: hello
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
