apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anchoring-secrets
  namespace: bitcert-attest
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bee-demo-store
  target:
    name: anchoring-secrets
  data:
  - secretKey: BITCERT_DATABASE_URL
    remoteRef:
      key: bitcert/dev/anchoring/db
      property: BITCERT_DATABASE_URL
  - secretKey: BITCERT_NATS_URL
    remoteRef:
      key: bitcert/dev/anchoring/nats
      property: BITCERT_NATS_URL
  - secretKey: BITCERT_PORT
    remoteRef:
      key: bitcert/dev/anchoring/net
      property: BITCERT_PORT
  - secretKey: BITCERT_NATS_STREAM
    remoteRef:
      key: bitcert/dev/anchoring/nats
      property: BITCERT_NATS_STREAM
  - secretKey: BITCERT_BITCOIND_RPC_URL
    remoteRef:
      key: bitcert/dev/anchoring/bitcoin
      property: BITCERT_BITCOIND_RPC_URL
  - secretKey: BITCERT_BITCOIND_RPC_USER
    remoteRef:
      key: bitcert/dev/anchoring/bitcoin
      property: BITCERT_BITCOIND_RPC_USER
  - secretKey: BITCERT_BITCOIND_RPC_PASSWORD
    remoteRef:
      key: bitcert/dev/anchoring/bitcoin
      property: BITCERT_BITCOIND_RPC_PASSWORD
