apiVersion: v1
kind: ConfigMap
metadata:
  name: web-grants
  namespace: bitcert-attest
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  R__grants.sql: 'DO $do$ BEGIN CREATE ROLE "bee_web"; EXCEPTION WHEN duplicate_object
    THEN NULL; END $do$;

    GRANT USAGE ON SCHEMA attest TO "bee_web";

    GRANT SELECT ON ALL TABLES IN SCHEMA attest TO "bee_web";

    ALTER DEFAULT PRIVILEGES IN SCHEMA attest GRANT SELECT ON TABLES TO "bee_web";

    '
