apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: ghcr.io/jbyee-test-org/bitcert/web@sha256:91a83d8cdd5b33f31c5421e4039a0203430a4fe6244a89249586e1e0719f9788
        ports:
        - containerPort: 8080
