apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: bitcert-attest
  labels:
    app.kubernetes.io/name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: ghcr.io/jbyee-test-org/bitcert/web@sha256:f59ab297e22c89794ec8d90bc3622c88466383e38c8f7b7cec1ab676f7c18926
        ports:
        - containerPort: 8080
